version: '3.8'

services:
  # Auth Service Infrastructure
  auth-db: 
    image: postgres:15-alpine
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db 
    ports:
      # HostPort: ContainerPort
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data 

  # Inventory Service Infrastructure
  inventory_db:
    image: postgres:15-alpine
    container_name: inventory_postgres
    restart: always
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
      POSTGRES_DB: inventory_db
    ports:
      - "5434:5432"


volumes:
  auth_db_data: