
services:
  # Auth Service Infrastructure
  auth-db: 
    image: postgres:15-alpine
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db 
    ports:
      # HostPort: ContainerPort
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data 

  # Inventory Service Infrastructure
  inventory_db:
    image: postgres:15-alpine
    container_name: inventory_postgres
    restart: always
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
      POSTGRES_DB: inventory_db
    ports:
      - "5434:5432"
    volumes:
      - inventory_db_data:/var/lib/postgres/data

  order_db:
    image: postgres:15-alpine
    container_name: order_postgres
    restart: always
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
      POSTGRES_DB: order_db
    ports:
      - "5435:5432"
    volumes:
      - order_db_data:/var/lib/postgres/data


volumes:
  auth_db_data:
  inventory_db_data:
  order_db_data: